### ISSUE TITLE
Using `.run` in `getServerSideProps` followed be returning a redirect will throw TypeError: argument entity is required

### ISSUE THREAD

**Issue by claudijo** [hoangvvo/next-connect#113]
Seems like redirecting by returning `{ redirect: destination: `/`, permanent: false}` from getServerSideProps after using `.run(req, res)` to get some session data does not work.

It throws `TypeError: argument entity is required` with the following stack trace (project specific root has been cleaned from the paths below):

```
at etag (/web-app-next/node_modules/next/dist/compiled/etag/index.js:1:783)
    at sendPayload (/web-app-next/node_modules/next/dist/next-server/server/send-payload.js:1:567)
    at DevServer.renderToHTMLWithComponents (/web-app-next/node_modules/next/dist/next-server/server/next-server.js:126:518)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async DevServer.renderToHTML (/web-app-next/node_modules/next/dist/next-server/server/next-server.js:127:711)
    at async DevServer.renderToHTML (/web-app-next/node_modules/next/dist/server/next-dev-server.js:34:578)
    at async DevServer.render (/web-app-next/node_modules/next/dist/next-server/server/next-server.js:70:236)
    at async Object.fn (/web-app-next/node_modules/next/dist/next-server/server/next-server.js:54:264)
    at async Router.execute (/web-app-next/node_modules/next/dist/next-server/server/router.js:24:67)
```

Running next version 10.0.1 and next-connect 0.9.1.

**Comment by claudijo** [comment]
Upgrading to next version 10.0.3 resolves this issue.
