### ISSUE TITLE
How to set errorHandler globally in v1?

### ISSUE THREAD

**Issue by larsqa** [hoangvvo/next-connect#201]
Before v1, i could create a base `nc` like
```js
export const nc = () =>
    nextConnect({
          onError: (err, req, res) => {
            console.error(err.stack);
            res.status(500).end("Something broke!");
          },
          onNoMatch: (req, res) => {
            res.status(404).end("Page is not found");
          },
    });
```

And then simply use `nc().get()`.

However, now in v1, router expects the errorHandling to be passed into the `router.handler()` method. Meaning, to achieve the same thing I would have to create an errorHandler object and pass it into the handler. This leads to two imports. Is it possible to set this on a base level?

```js
// Not what i want, but current behavior
const errorHandling = {
          onError: (err, req, res) => {
            console.error(err.stack);
            res.status(500).end("Something broke!");
          },
          onNoMatch: (req, res) => {
            res.status(404).end("Page is not found");
          },
}


...
// another file
import {router, errorHandling} from "./my-next-connect.js"
export default router.handler(errorHandling)
```

**Comment by hoangvvo** [comment]
That is an error on the doc, which I have removed. Unfortunately this is intended, providing options as part of nextConnect() is a bit misleading since calling .run() does not really respect these option, so I make it explicit that only .handler() will repsect it, thus the fact that it is only there.

Perhaps you can try something like below:

```js
export const nc = () => {
  const router = createRouter();
  const handler = router.handler.bind(handler);
  // rewrite router.handler so that when you call it, it is called with the options
  router.handler = () => handler({ ...yourOptions });
  return router;
};
```

**Comment by larsqa** [comment]
Isn't
```js
const router = createRouter();
const handler = router.handler.bind(handler);
```
wrong? Isn't it supposed to be

```js
const router = createRouter();
const handler = router.handler.bind(router);
```

**Comment by larsqa** [comment]
Agree with @hussamkhatib, the new approach introduces more friction. I'd like to use it as it was before.

**Comment by IRediTOTO** [comment]
I like previous features too. I don't dare update Nc newest version :\

**Comment by raphaelbadia** [comment]
> That is an error on the doc, which I have removed. Unfortunately this is intended, providing options as part of nextConnect() is a bit misleading since calling .run() does not really respect these option, so I make it explicit that only .handler() will repsect it, thus the fact that it is only there.
> 
> Perhaps you can try something like below:
> 
> ```js
> export const nc = () => {
>   const router = createRouter();
>   const handler = router.handler.bind(router);
>   // rewrite router.handler so that when you call it, it is called with the options
>   router.handler = () => handler({ ...yourOptions });
>   return router;
> };
> ```

Tried this, and it works perfectly. Thanks !

**Comment by nemanjahifolks** [comment]
This is not an elegant solution because now in every api route file I need to export this:

```ts
export default handler.handler();
```
instead of nicer:

```ts
export default handler;
```

or I get this error:

```
error - Error [TypeError]: resolver is not a function
    at /home/username/Desktop/folks/node_modules/next/dist/server/api-utils/node.js:377:16
    at /home/username/Desktop/folks/node_modules/next/dist/server/lib/trace/tracer.js:92:36
    at NoopContextManager.with (/home/username/Desktop/folks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/home/username/Desktop/folks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
```
How to fix this?
